developing: added css properties for header block
AlexanderBazukevich/Passion pull request #4
Opened 2019-09-10 15:38 UTC by AlexanderBazukevich

2019-09-10 18:11 UTC, denisnarush requested changes

2019-09-10 18:11 UTC, denisnarush commented on passion.css
> +    margin: 8% 15% 6% 15%;
WTF IS IT ?

2019-09-10 18:11 UTC, denisnarush commented on passion.css
> +    background-image: url(img/billboard.jpg);
Your commit doesn't contains pictures files. Please add images to commit

2019-09-10 18:11 UTC, denisnarush commented on passion.css
> +    width: 850px;
what is the problem to add `width` property to the body and do not `ctrl + c` + `ctrl + v` this line in other 5+ blocks ?

2019-09-10 18:11 UTC, denisnarush commented on passion.css
> +    margin-right: auto;
`margin: 0 auto` to combine this two lines

2019-09-10 18:11 UTC, denisnarush commented on passion.css
> +    height: 20%;
not possible to use normally height with percentage value. remove please this line

2019-09-10 20:38 UTC, AlexanderBazukevich commented on passion.css
> +    margin: 8% 15% 6% 15%;
Separate this in 4 lines?

2019-09-11 05:54 UTC, denisnarush commented on passion.css
> +    margin: 8% 15% 6% 15%;
Answered in telegram chat

2019-09-11 05:55 UTC, denisnarush requested changes

2019-09-11 05:55 UTC, denisnarush commented on index.html
> +            <a class="logo logo_center" href="/"><img class="logo__image logo__image_big" src="img/header_logo.png"></a>
logo not loaded

2019-09-12 09:23 UTC, denisnarush requested changes

2019-09-12 09:23 UTC, denisnarush commented on passion.css
> +    margin: auto;
should be `margin: 0 auto`

2019-09-12 09:23 UTC, denisnarush commented on passion.css
>      background-image: url(billboard.jpg);
change to `padding: 0 125px`

2019-09-12 09:23 UTC, denisnarush commented on passion.css
> +    margin: auto;
is `margin: auto;` needed here?

2019-09-12 09:23 UTC, denisnarush commented on passion.css
> +    padding-right: 100px;
`margin` - is a combined property of 4 side margins. `margin: top right bottom left`
so why you are using 3 lines instead of one?
`margin: 0 100px 50px 0;`

2019-09-12 09:23 UTC, denisnarush commented on passion.css
> +    font-family: Raleway;
if element can be clicked like a button, cursor should be set value different from default text selection. For example `cursor: pointer`;
also, if you are using `<a>` tag, you should always set `href` attribute. For example `<a href="#">`

2019-09-12 09:23 UTC, denisnarush commented on index.html
> +        </div>
whitespaces

2019-09-12 09:23 UTC, denisnarush commented on index.html
> +	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
i see tab instead of whitespaces

2019-09-12 11:12 UTC, AlexanderBazukevich commented on passion.css
> +    padding-right: 100px;
because of not clearly understanding of using shorthand declaration in different situations (when it's good to separate or not)

2019-09-12 15:59 UTC, denisnarush commented on passion.css
> +    padding-right: 100px;
lets discuss next time this point

2019-09-16 15:15 UTC, denisnarush approved these changes
You can merge after fixing minor changes without my next review

2019-09-16 15:15 UTC, denisnarush commented on passion.css
> +    line-height: 44px;
Try to use decimal value for `line-height`

2019-09-16 15:15 UTC, denisnarush commented on passion.css
> +    letter-spacing: 1px;
:47 line is in _em_ but :60 line in _px_.. Hm..

2019-09-16 19:00 UTC, merged